version: "3.9"
services:
  phpexample:
    image: phpexample
    container_name: phpexample
    build:
      network: host
      dockerfile: 'DockerFile'
    ports:
      - '8080:8080'
    volumes:
      - ./src:/var/www/html
